### ISSUE TITLE
Can i Enable Console Logging For All Requests?

### ISSUE THREAD

**Issue by mahmoudshurrabkryptonic** [allaboutapps/Fetch#35]
Hello,

After i upgrade Fetch for latest version i miss the logging, but on old version it is showing console logs.

So shall i do some configuration to enable it again, or it is disabled on new version?

Looking forward for your help.

Thanks

**Comment by mbuchetics** [comment]
Hi,
I just checked out the latest version 3.1.5 with the included GithubExample and logging seems to work fine there.

**Comment by mahmoudshurrabkryptonic** [comment]
> 

Thank you for your response,

I have select version 3.1.5 but it is same issue.

shall i do some configuration or it is automatically enabled?

**Comment by mahmoudshurrabkryptonic** [comment]
> Hi, I just checked out the latest version 3.1.5 with the included GithubExample and logging seems to work fine there.

Thank you for your response,

I have select version 3.1.5 but it is same issue.

shall i do some configuration or it is automatically enabled?

**Comment by mbuchetics** [comment]
It should be automatically enabled. How does your APIClient configuration look like? Have you tried the examples to check wether it works there? Which version of Xcode are you using? I have tested with Xcode 14.3.1

**Comment by mahmoudshurrabkryptonic** [comment]
> It should be automatically enabled. How does your APIClient configuration look like? Have you tried the examples to check wether it works there? Which version of Xcode are you using? I have tested with Xcode 14.3.1

Yes sure i am using Xcode 14.3.1

Here is my APIClient Configuration

`static func prepareAPI() {
        let config = Config(baseURL: URL(string: APIConstants.API.BASE_URL_WITH_API)!,
                            defaultHeaders: generateDefaultHeaders(),
                            timeout: 60,
                            eventMonitors: [],
                            interceptor: APIInterceptor(),
                            cache: nil,
                            cachePolicy: .networkOnlyNoCache)
        
        APIClient.shared.setup(with: config)
    }`
    
    Is there is any config i need to add?

**Comment by mbuchetics** [comment]
You should not set an empty array for the `eventMonitors`. The logging is implemented as an Event Monitor, see https://github.com/allaboutapps/Fetch/blob/18c9251d5b49f3d1133f2c1faf8e57ff0c02b892/Sources/Fetch/Network/APIClient.swift#L56

You can provide `[APILogger(verbose: true)]` or you delete the line and the default parameter will be used.

**Comment by mahmoudshurrabkryptonic** [comment]
> You should not set an empty array for the `eventMonitors`. The logging is implemented as an Event Monitor, see
> 
> https://github.com/allaboutapps/Fetch/blob/18c9251d5b49f3d1133f2c1faf8e57ff0c02b892/Sources/Fetch/Network/APIClient.swift#L56
> 
> You can provide `[APILogger(verbose: true)]` or you delete the line and the default parameter will be used.

I see, it is working fine now, sorry for that, and i am really appreciate your help.

**Comment by mahmoudshurrabkryptonic** [comment]
It is fixed now with @mbuchetics help.

**Comment by mbuchetics** [comment]
No problem, I hope you enjoy using Fetch!
